name: Continuous Integration and Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
      
  docker:

    needs: build
    runs-on: self-hosted
    
    steps:
      - name: build webapp image
        run: sudo docker build -t webapp:latest .
      - name: build Api image
        working-directory: ./BlockchainDemonstratorApi
        run: sudo docker build -t api:latest .
