name: Continuous Integration and Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
      
  docker:

    needs: build
    runs-on: ubuntu-latest
    
    steps:
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
         buildkitd-flags: --debug
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: .
          tags: user/app:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
