name: Continuous Integration and Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
      
  docker:

    needs: build
    runs-on: self-hosted
    
    steps:
      - name: build webapp image
        run: sudo docker build --rm -t webapp:latest .
          
      - name: update appsettings.json
        working-directory: ./BlockchainDemonstratorApi
        run: echo "`jq '.ConnectionStrings.BeerGameContext ="Server=172.17.0.2;Database=BeerGameContext;Trusted_Connection=True;MultipleActiveResultSets=true;User id=${{ secrets.DB_USER_ID }};Password=${{ secrets.DB_USER_PASSWORD }};Integrated Security=false"' appsettings.json`" > appsettings.json
        
      - name: build Api image
        working-directory: ./BlockchainDemonstratorApi
        run: sudo docker build --rm -t api:latest .
        
      - name: prune docker images
        run: sudo docker image prune -f
